INSERT INTO SongList (Song,Singer,Activ) VALUES (N'Полина Гагарина',N'Кукушка',1)
INSERT INTO SongList (Song,Singer,Activ) VALUES (N'Полина Гагарина',N'Шагай',1)
INSERT INTO SongList (Song,Singer,Activ) VALUES (N'Полина Гагарина',N'Стану Солнцем',1)
INSERT INTO SongList (Song,Singer,Activ) VALUES (N'Полина Гагарина',N'Нет',1)
INSERT INTO SongList (Song,Singer,Activ) VALUES (N'Полина Гагарина',N'Нет',1)
INSERT INTO SongList (Song,Singer,Activ) VALUES (N'SHAMAN',N'Я Русский!',1)
INSERT INTO SongList (Song,Singer,Activ) VALUES (N'SHAMAN',N'Встанем',1)
